
# Project information

site_name: Google SecOps ハンズオン
site_short_name: SecOps ハンズオン
site_description: 'このハンズオンセミナーは Google Security Operations を利用して、AI を搭載したインテリジェンス主導のセキュリティ運用基盤に関連する様々な活用方法を体験します'
# site_author: ''
# site_url: ''
# copyright: ''


# Configuration
theme: 
  # name: readthedocs
  name: material
  language: ja
  font: 
    text: Noto Sans JP
    code: JetBrains Mono

  # feature:
  #   tabs: true
  # favicon: ico/ki.png


# Extensions
markdown_extensions:
  - admonition
  # - pymdownx.details

# Navigation
nav:
  - 概要: 'index.md'
  - 'AI (Gemini) 機能': 
    - '1. SecOpsへのアクセス': 'gemini/01-access.md'
    - '2. ログの確認': 'gemini/02-dashboard.md'
    - '3. 基本操作': 
      - '3.1. ログの検索': 'gemini/031-search.md'
      - '3.2. 検索結果の確認': 'gemini/032-check-results.md'
    - '4. Gemini活用': 
      - '4.1. テンプレートの利用': 'gemini/041-template.md'
      - '4.2. 脅威ハンティング': 'gemini/042-threathunt.md'
      - '4.3. ログ調査支援': 'gemini/043-create-query.md'
    - '5. SOAR機能': 'gemini/05-soar.md'

    - '6. まとめ': 'gemini/06-summary.md'

